import { Inter } from "next/font/google";
import "./../globals.css";
import { CssBaseline } from "@mui/material";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
          {" "}
          <div>Nav</div>
          <CssBaseline />
          {children}
      </body>
    </html>
  );
}
