'use client'
import { grayColor } from "@/constants/color";
import { Typography , Box } from "@mui/material";
import axios from "axios";
import { useEffect } from "react";
import { userExits, userNotExists } from "@/redux/reducers/auth";
import { useDispatch } from "react-redux";

// export const metadata = {
//   title: "Convo-Net",
//   description: "Generated by create next app",
// };

export default function Home() {
  const server = process.env.NEXT_PUBLIC_SERVER;

  const dispatch = useDispatch();


  useEffect(() => {
    axios
      .get(`${server}/user/profile`, { withCredentials: true })
      .then((res) => {
       dispatch(userExits(res.data.data));
       console.log(res, "reached");
      })
      .catch((err) => {
        dispatch(userNotExists());
      });
  }, []);
  return (
    <Box bgcolor={grayColor} height={"100%"}>
      {" "}
      <Typography p={"2rem"} variant="h5" textAlign={"center"}>
        Select a friend to chat
      </Typography>
    </Box>
  );
}
