import { grayColor } from "@/constants/color";
import { Typography , Box } from "@mui/material";
import Head from "next/head";
import Image from "next/image";

export const metadata = {
  title: "Convo-Net",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <Box bgcolor={grayColor} height={"100%"}>
      {" "}
      <Typography p={"2rem"} variant="h5" textAlign={"center"}>
        Select a friend to chat
      </Typography>
    </Box>
  );
}
