import Head from "next/head";
import Image from "next/image";

export const metadata = {
  title: "Convo-Net",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <div>
      <h1>Home</h1>
     
    </div>
    </>
  );
}
